name: Converter to AsciiDocs

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  convert-to-ascii_doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Pandocs
        run: sudo apt-get install -y pandoc

      # Runs a set of commands using the runners shell
      - name: Use Pandoc for conversion
        run: |
          pandoc -t asciidoc -f markdown README.md > README.asciidoc
          ls -s README.asciidoc
          
      - name: Setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: commit
        run: |
          git add README.asciidoc
          git commit -m "Update ascii docs"
          git push origin master
          
