name: Converter to AsciiDocs

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  convert-to-ascii_doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Pandocs
        run: sudo apt-get install -y pandoc

      - name: Use Pandoc for conversion
        run: |
          pandoc -t asciidoc -f markdown README.md > README.asciidoc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "push it all "
          commit_user_name: Cedrick Lunven
          commit_user_email: cedrick.lunven@gmail.com
          commit_author: Cedrick Lunven<cedrick.lunven@gmail.com>
