name: Converter to AsciiDocs

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  convert-to-ascii_doc:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Pandocs
        run: sudo apt-get install -y pandoc

      # Runs a set of commands using the runners shell
      - name: Use Pandoc for conversion
        run: |
          pandoc -t asciidoc -f markdown README.md > README.asciidoc
          ls -l README.md 
          ls -l README.asciidoc
          
      - name: Commit new files
        run: |
          # Stage the file, commit and push
          git add README.asciidoc
          git commit -m "Update ascii docs"
          git push origin master
          
