name: Converter to AsciiDocs

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Pandocs
        run: sudo apt-get install -y pandoc

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pandoc -t asciidoc -f markdown README.md > README.asciidoc
          echo test, and deploy your project.
